name: Custom Deployment

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push to gh-pages
      env:
        FOLDER_NAME: files
      run: |
        sudo apt update
        sudo apt install -y tree
        tree $FOLDER_NAME -H . -o $FOLDER_NAME/index.html
        git config user.name DevrajDC
        git add $FOLDER_NAME/index.html
        git commit --amend --no-edit
        git push origin `git subtree split --prefix $FOLDER_NAME main`:gh-pages --force ||  git subtree push --prefix $FOLDER_NAME origin gh-pages
